### ISSUE TITLE
Balancer AMM contract does not work for non-compliant ERC20 tokens like USDT

### ISSUE THREAD

**Issue by maarcweiss** [raft-fi/contracts#302]
## TITLE (Contract does not work for non-compliant ERC20 tokens like USDT)

Certain older tokens are not perfectly compliant with the ERC20 standard. Most notably is USDT. Not only does it not return a success boolean whenever an operation is done, it also reverts if someone tries to approve from a non-zero allowance to another non-zero allowance.

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/AMMs/BalancerAMM.sol#L49

## SEVERITY

Medium. 

## A LINK TO THE GITHUB ISSUE
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/AMMs/BalancerAMM.sol#L49

## SOLUTION

Use safeApprove instead of approve:

           tokenIn.safeApprove(address(vault), amountIn);

**Comment by maarcweiss** [comment]
The issue is a medium standardized by all the industry, one of the dozens of examples: https://solodit.xyz/issues/805  Please consider changing the severity, thanks!

**Comment by mijovic** [comment]
Fixed by #376
