### ISSUE TITLE
ChainlinkPriceOracle deviation formula can lead to invalid responses being accepted

### ISSUE THREAD

**Issue by aviggiano** [raft-fi/contracts#305]
# ChainlinkPriceOracle deviation formula can lead to invalid responses being accepted

[`ChainlinkPriceOracle._chainlinkPriceChangeAboveMax`](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/ChainlinkPriceOracle.sol#L156-L161) uses the larger price as the denominator in order to calculate the deviation percent between the current and previous responses. However, this can lead to invalid responses being accepted.

# Severity

Medium

# Affected smart contract

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/ChainlinkPriceOracle.sol#L156-L161

# Description

The `ChainlinkPriceOracle` deviation formula uses the larger price as the denominator in order to calculate the deviation percent, explaining that if price decreased, the percentage deviation is in relation to the previous price, and if the price increased, the percentage deviation is in relation to the current price.

However, this can lead to invalid responses being accepted in the case where the current price is bigger than the previous price. 

The reason is that the price reported on the _current_ round (round `N`) is still subject to validation, while the price on the _previous_ round (round `N-1`) will have already been accepted, and will have already been validated by its _previous_' previous round (round `N-2`). This is why the previous round should be trusted as the base price for the denominator.

# Attack scenario

Assume the `MAX_PRICE_DEVIATION_FROM_PREVIOUS_ROUND` parameter is equal to `25%`, and the following datapoints are reported by the oracle:

| Round Index | Price | `percentDeviation` | Deviation With Regard To Previous Round |
| ----------- | ----- | ------------------ | --------------------------------------- |
| 1           | 100   | N/A                | N/A                                     |
| 2           | 103   | 2.9%               | 3.0%                                    |
| 3           | 100   | 2.9%               | 2.9%                                    |
| 4           | 130   | 23.1%              | 30.0%                                   |

As it can be seen, the round data number 4 should not be accepted as a valid price, since it is 30% greater than the previous "correct" price. Because of the incorrect formula, it will be accepted, which may lead to unexpected consequences, such as liquidations.

# Recommendation

Consider the previous round as the denominator for the deviation percentage.

**Comment by StefanVitor** [comment]
Fixed by #342
