### ISSUE TITLE
Gas Optimisation Report

### ISSUE THREAD

**Issue by pavankv241** [raft-fi/contracts#354]
Gas optimisation 

[liquadtion()](https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L189) function

## 1 .Use x = x - y instead of x-=y for state varibles to save gas :-

code snippet :-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L212

## 2.Use unchecked block can save gas upto 100 .
Solidity version 0.8+ comes with implicit overflow and underflow checks on unsigned integers. When an overflow or an underflow isn’t possible (as an example, when a comparison is made before the arithmetic operation), some gas can be saved by using an unchecked block: https://docs.soliditylang.org/en/v0.8.7/control-structures.html#checked-or-unchecked-arithmetic

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L212.

## 3. Check Zero value before transfer 
SafeTransfer()  will not work on zero value but when zero value passed to SafeTransfer() function it will not return gas .So before check value will save some gas.

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L216

## 4 .Use assembly to check for address(0)

Saves 6 gas per instance

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L191

-----------------------------------------------------------------------------------------
[managaePosition()](https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L129) function 

## 1 Use nested if else statement to save gas :-
Using nested is cheaper than using && multiple check combinations. There are more advantages, such as easier to read code and better coverage reports.

saves 9 gas per instnace.

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L150
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L147
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L158 

## 2 . Sometimes != is cheaper than > 

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L144

## 3. Use constants instead of type(uintx).max
type(uint256).max uses more gas in the distribution process and also for each transaction than constant usage

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L158

## 4 .No need to evaluate all expressions to know if one of them is true
When we have a code expressionA || expressionB if expressionA is true then expressionB will not be evaluated and gas saved

code snippet:-
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L159

change to :-
if (isCollateralIncrease ||collateralChange != 0 )

**Comment by mijovic** [comment]
Can you share a PR showing there is at least 5% improvement to gas numbers for liquidate function?
