### ISSUE TITLE
TellorPriceOracle might not work as expect

### ISSUE THREAD

**Issue by web3layman000** [raft-fi/contracts#359]
# Summary
[TellorPriceOracle](https://github.com/raft-fi/contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/TellorPriceOracle.sol#L9) uses Tellor as price oracle, after checking [TellorFlex](https://etherscan.io/address/0xD9157453E2668B2fc45b7A803D3FEF3642430cC0#readContract), it seems that  [TellorFlex](https://etherscan.io/address/0xD9157453E2668B2fc45b7A803D3FEF3642430cC0#readContract) might not working as expect.

# Vulnerability Details
According to the code https://github.com/raft-fi/contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/TellorPriceOracle.sol#L16

`STETH_TELLOR_QUERY_ID` should be `0x907154958baee4fb0ce2bbe50728141ac76eb2dc1731b3d40f0890746dd07e62`

In function `_getCurrentTellorResponse` https://github.com/raft-fi/contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/TellorPriceOracle.sol#L45-L61 

The function call `tellor.getNewValueCountbyQueryId(STETH_TELLOR_QUERY_ID)` to get `count`,  so we can call the same function  with `0x907154958baee4fb0ce2bbe50728141ac76eb2dc1731b3d40f0890746dd07e62` as `_queryId` [on etherscan](https://etherscan.io/address/0xD9157453E2668B2fc45b7A803D3FEF3642430cC0#readContract),  the function returns `2` as `count`

Then we contine call `getTimestampbyQueryIdandIndex(STETH_TELLOR_QUERY_ID, count - 1)` using `0x907154958baee4fb0ce2bbe50728141ac76eb2dc1731b3d40f0890746dd07e62` as `_queryId` and `1` as `_index`, [etherscan](https://etherscan.io/address/0xD9157453E2668B2fc45b7A803D3FEF3642430cC0#readContract) returns `1680314939`

`1680314939` is `Sat Apr  1 03:08:59 BST 2023`, which is more than one month from now.
So [BasePriceOracle._oracleIsFrozen](https://github.com/raft-fi/contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/BasePriceOracle.sol#L33-L35) will always return true

# Severity
Medium

**Comment by mijovic** [comment]
I think you are missing how Tellor price oracle works. In order to get the price updates, we need to tip the oracle, which will be the automated process.

**Comment by mijovic** [comment]
Right now, nobody is using Tellor stETH oracle, this is why the data is very outdated
