### ISSUE TITLE
Minting exposes users to unlimited slippage

### ISSUE THREAD

**Issue by htstarz** [raft-fi/contracts#365]
**_DESCRIPTION_**
Position manager uses both minting functions of _Rtoken.sol_ and _erc20indexible.sol_  to mint _rtokens_  when adding debt change and _raftcollateraltokens_  when adding collateral change. These functions however only specify the amount to minted meaning users may receive less or more _rtokens_ or less or more "collateral change" .

**_CODE SNIPPET_**
**_Rtoken.sol_**
 function mint(address to, uint256 amount) external override onlyPositionManager {
        _mint(to, amount);
    }

**_erc20indexible.sol_**
 function mint(address to, uint256 amount) external override onlyPositionManager {
        _mint(to, amount.divUp(currentIndex));
    }
**_RECOMMENDATION_**
consider adding slippage parameters to both functions to prevent users from being exposed to effects of unlimited [slippage.

**Comment by mijovic** [comment]
There is no slippage here at all. For example, Raft Collateral tokens are minted with the exact same value as collateral tokens deposited. Same goes for debt + R. You can compare this to aTokens in Aave.

Closing as invalid.

**Comment by htstarz** [comment]
Then that will mean that there are no swaps between eth, seth and wseth with rtokens for example therefore any amount can be input-ed.
