### ISSUE TITLE
Gas report

### ISSUE THREAD

**Issue by rotcivegaf** [raft-fi/contracts#369]
## [G-01] Add `unchecked {}` in operations where the operands cannot over/underflow

The `lastFeeOperationTime` cannot be greater than `block.timestamp`, at most equal(Look [L548](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L548))

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L545
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L554

## [G-02] Avoid use `modifier`

Move the behavior to the function or encapsulate the behavior of the modifier in a internal function

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L62-L107

## [G-03] Use `!= 0` instead of `> 0` for unsigned integer comparison

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L144

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L573

## [G‑04] Splitting `require()`/`if()` statements that use `&&` saves gas

See [this issue](https://github.com/code-423n4/2022-01-xdefi-findings/issues/128) which describes the fact that there is a larger deployment gas cost, but with enough runtime calls, the change ends up being cheaper by 3 gas

From:
```solidity
if(a && b) {
    ...
}
```
To:
```solidity
if(a) {
    if(b) {
        ...
    }
}
```

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L78
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L89-L92
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L103
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L147
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L150
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L158

## [G‑05] Splitting `if()` statements that use `||` saves gas

From:
```solidity
if(a || b) {
    <CODE>
}
```
To:
```solidity
if(a) {
    <CODE>
}
if(b) {
    <CODE>
}
```

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L159
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L241

## [G‑06] Caching in local variable to avoid `SLOAD`

Cache `collateralTokenForPosition[position]`:
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L90-L91

Cache `raftCollateralTokens[collateralToken]` and `raftCollateralTokens[collateralToken].token`:
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L162
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L170

Cache `raftDebtToken`:
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L157
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L169
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L192
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L198

## [G‑07] Send `raftCollateralTokens[collateralToken].token` as a parameter in the function `_adjustCollateral`

After **G-06** send the `token`(`raftCollateralTokens[collateralToken].token`) as a parameter in the function `_adjustCollateral` to save the `SLOAD`

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L167
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L451-L472

## [G‑08] Mix `if()` statements

a)
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L142
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L102-L107
```solidity
isDebtIncrease && (maxFeePercentage < borrowingSpread || maxFeePercentage > MathUtils._100_PERCENT)
```
b)
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L144
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L77-L82
```solidity
isDebtIncrease && debtChange > 0  && !raftCollateralTokens[collateralToken].isEnabled
```
a mix b)
```solidity
isDebtIncrease &&
    (maxFeePercentage < borrowingSpread || maxFeePercentage > MathUtils._100_PERCENT) &&
    debtChange > 0 &&
    !raftCollateralTokens[collateralToken].isEnabled
```

## [G‑09] Send `raftCollateralTokens[collateralToken].token` as a parameter in the functions `_closePosition`, `liquidate` and `_updateDebtAndCollateralIndex`

After **G-06** send the `token`(`raftCollateralTokens[collateralToken].token`) as a parameter in the function `_closePosition` to save the `SLOAD`

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L177
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L481-L489

In the `liquidate` function
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L217

And in the `_updateDebtAndCollateralIndex` function
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L219

## [G‑10] Cached `LOW_TOTAL_DEBT` in a local var

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L582

The `LOW_TOTAL_DEBT` of `splitLiquidationCollateral` contract could be cached in storage, saving the call(2100 gas) to `splitLiquidationCollateral` contract:

```solidity
@@ -49,6 +49,7 @@ contract PositionManager is FeeCollector, IPositionManager {
     mapping(address position => mapping(address delegate => bool isWhitelisted)) public override isDelegateWhitelisted;

     ISplitLiquidationCollateral public override splitLiquidationCollateral;
+    uint256 private LOW_TOTAL_DEBT;

     uint256 public override borrowingSpread;
     uint256 public override redemptionSpread;
@@ -364,6 +365,7 @@ contract PositionManager is FeeCollector, IPositionManager {
             revert SplitLiquidationCollateralCannotBeZero();
         }
         splitLiquidationCollateral = newSplitLiquidationCollateral;
+        LOW_TOTAL_DEBT = newSplitLiquidationCollateral.LOW_TOTAL_DEBT();
         emit SplitLiquidationCollateralChanged(newSplitLiquidationCollateral);
     }

@@ -579,7 +581,7 @@ contract PositionManager is FeeCollector, IPositionManager {
     // --- Validation check helper functions ---

     function _checkValidPosition(IERC20 collateralToken, uint256 positionDebt, uint256 positionCollateral) internal {
-        if (positionDebt < splitLiquidationCollateral.LOW_TOTAL_DEBT()) {
+        if (positionDebt < LOW_TOTAL_DEBT) {
             revert NetDebtBelowMinimum(positionDebt);
         }
```

>> NOTE: These changes are not in the pull request, given the tests the gas used increases, but with more calls it should decrease

## [G‑11] Save sub in a local var and emit

Save `_totalDebt - entirePositionDebt` in a var an use it for `_totalDebt` assign and `TotalDebtChanged` event emit
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L208-L209

## [G‑12] Remove the `_closePosition` function and move it behavior inside the functions that uses it

https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L177
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L217
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L481-L489

# Gas reports:

Before optimization:
| contracts/PositionManager.sol:PositionManager contract |                 |        |        |        |         |
|--------------------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                                        | Deployment Size |        |        |        |         |
| 5282759                                                | 28492           |        |        |        |         |
| Function Name                                          | min             | avg    | median | max    | # calls |
| liquidate                                              | 5478            | 30031  | 43775  | 68235  | 23      |
| managePosition                                         | 1496            | 127866 | 107347 | 265628 | 174     |

After optimization:
| contracts/PositionManager.sol:PositionManager contract |                 |        |        |        |         |
|--------------------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                                        | Deployment Size |        |        |        |         |
| 5207671                                                | 28117           |        |        |        |         |
| Function Name                                          | min             | avg    | median | max    | # calls |
| liquidate                                              | 5424            | 29736  | 43316  | 67807  | 23      |
| managePosition                                         | 774             | 127125 | 106468 | 264749 | 174     |

**Comment by mijovic** [comment]
?

**Comment by rotcivegaf** [comment]
In order not to reveal my report and to be able to send the hats finance submission
I reserved this issue spot
I'll edit it before competition is over

**Comment by mijovic** [comment]
The improvement in both functions is irrelevant. We are interested only in 5% + improvements
