### ISSUE TITLE
PositionManager.sol#LL189C14-L189C23 : dust amount could be left in contract which can grow during each liquidation. This never be utilized.

### ISSUE THREAD

**Issue by aktech297** [raft-fi/contracts#372]
`Severity:`

Medium

`Summary`

Dust amount can be left during liquidation due to truncation while calculating the liquidation and liquidating fee share.

`Issue details:`

when liquidation happens. below line of codes executed to decide the following shares

collateralLiquidationFee, collateralToSendToLiquidator

        (uint256 collateralLiquidationFee, uint256 collateralToSendToLiquidator) =
            splitLiquidationCollateral.split(entirePositionCollateral, entirePositionDebt, price, isRedistribution);

when we look at the function `split`, it has the truncation logic to decide the share.

lets check at the function call.

    null(
        uint256 totalCollateral,
        uint256 totalDebt,
        uint256 price,
        bool isRedistribution
    )
        external
        pure
        returns (uint256 collateralToSendToProtocol, uint256 collateralToSentToLiquidator)
    {
        if (isRedistribution) {
            uint256 collateralValue = totalCollateral.mulDown(price);
            uint256 rewardRate = _calculateRedistributorRewardRate(collateralValue);
            collateralToSentToLiquidator = totalCollateral.mulDown(rewardRate);
        } else {
            uint256 matchingCollateral = totalDebt.divDown(price);
            uint256 excessCollateral = totalCollateral - matchingCollateral;
            uint256 liquidatorReward = excessCollateral.mulDown(_calculateLiquidatorRewardRate(totalDebt));
            collateralToSendToProtocol = excessCollateral - liquidatorReward;
            collateralToSentToLiquidator = liquidatorReward + matchingCollateral;
        }

incase the isRedistribution== false, the else part is executed and the share is calculated by some of the divide down logic . this would lead to truncation of values.

Since the truncation happens ,

the sum of collateralLiquidationFee and collateralToSendToLiquidator will not be equal to entirePositionCollateral.

        (uint256 collateralLiquidationFee, uint256 collateralToSendToLiquidator) =
            splitLiquidationCollateral.split(entirePositionCollateral, entirePositionDebt, price, isRedistribution);

this means, there will be dust amount will be left during each liquidation.

when liquidation is more, the dust amount will be accumulated which would be left without liquidation.

`Remediation`

Introduce new state variable and track these left out collateral value.
During each liquidation, the dust value could be accumulated. Later on if needed, anyone or owner can withdraw this collateral value.
So that 

  uint  New_vairbale += entirePositionCollateral - (collateralLiquidationFee+collateralToSendToLiquidator);

**Comment by mijovic** [comment]
This is not true. We even run fuzzing on this particular scenario, there was not a single edge case.
