### ISSUE TITLE
OneStepLeverageStETH.sol: Typecast the wstETH_ during the OneStepLeverageStETH contract creation

### ISSUE THREAD

**Issue by aktech297** [raft-fi/contracts#373]
constructor(
        IPositionManager positionManager_,
        IAMM amm_,
        IWstETH wstETH_
    )
        OneStepLeverage(positionManager_, amm_, wstETH_)
        WstETHWrapper(wstETH_)

above constructor code executed when `OneStepLeverageStETH` contract is created.

But when we look at the third argument from `OneStepLeverage` its IERC20 token address

    constructor(
        IPositionManager positionManager_,
        IAMM amm_,
        IERC20 collateralToken_

contract creation without proper typecase can cause any unexpected issues.

**Comment by mijovic** [comment]
IWstETH inherits from IERC20
